services:
  mongo-config-server:
    container_name: mongo-config-1
    image: dh-mirror.gitverse.ru/mongo:latest
    restart: always
    volumes:
      - config-data:/data/db
    command:
      [
        "--configsvr",
        "--replSet",
        "config_server",
        "--bind_ip_all",
        "--port",
        "27017"
      ] 
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  mongo-shard-01:
    image: mongo:latest
    container_name: shard-01
    restart: always
    volumes:
      - shard1-data:/data/db
    command:
      [
        "--shardsvr", 
        "--replSet",
        "shard-01",
        "--bind_ip_all",
        "--port",
        "27018"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  mongo-shard-02:
    image: mongo:latest
    container_name: shard-02
    restart: always
    volumes:
      - shard2-data:/data/db
    command:
      [
        "--shardsvr", 
        "--replSet",
        "shard-02",
        "--bind_ip_all",
        "--port",
        "27019"
      ]
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  mongos-router:
    image: dh-mirror.gitverse.ru/mongo:latest
    container_name: mongo-router-1
    restart: always
    command:
      [
        "mongos", 
        "--configdb", 
        "config_server/mongo-config-server:27017",
        "--bind_ip_all",
        "--port",
        "27020"
      ]
    depends_on:
      - mongo-shard-01
      - mongo-shard-02
      - mongo-config-server
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 5s
      start_period: 10s

  pymongo-api:
    container_name: pymongo_api
    build: 
      context: api_app
      dockerfile: Dockerfile
    image: kazhem/pymongo_api:1.0.0
    depends_on:
      - mongos-router
    ports:
      - 8080:8080
    environment:
      MONGODB_URL: "mongodb://mongos-router:27020"
      MONGODB_DATABASE_NAME: "somedb"


volumes:
  config-data:
  shard1-data:
  shard2-data: